
import 'dart:math';

const String _assetPath = 'assets/images/icons/illustrations';

final class IllustrationAssets {
  static const List<String> illustrations = [
    '$_assetPath/2.png',
    '$_assetPath/3.png',
    '$_assetPath/4.png',
    '$_assetPath/5.png',
    '$_assetPath/6.png',
    '$_assetPath/7.png',
    '$_assetPath/8.png',
    '$_assetPath/10.png',
    '$_assetPath/12.png',
    '$_assetPath/13.png',
    '$_assetPath/14.png',
    '$_assetPath/15.png',
    '$_assetPath/20.png',
    '$_assetPath/Apple.png',
    '$_assetPath/Balloon.png',
    '$_assetPath/Bolt.png',
    '$_assetPath/Boot.png',
    '$_assetPath/Box.png',
    '$_assetPath/Box-1.png',
    '$_assetPath/Bubble.png',
    '$_assetPath/Bubble-1.png',
    '$_assetPath/Bubble-2.png',
    '$_assetPath/Bubble-3.png',
    '$_assetPath/Bubble-4.png',
    '$_assetPath/Bubble-5.png',
    '$_assetPath/Bubble-6.png',
    '$_assetPath/Bubble-7.png',
    '$_assetPath/Cactus.png',
    '$_assetPath/Cherries.png',
    '$_assetPath/Circle.png',
    '$_assetPath/Circle-1.png',
    '$_assetPath/Clock.png',
    '$_assetPath/Cloud.png',
    '$_assetPath/Cloud Bubble.png',
    '$_assetPath/Cloud Bubble-1.png',
    '$_assetPath/Cloud Bubble-2.png',
    '$_assetPath/Cloud Bubble-3.png',
    '$_assetPath/Cloud Rainbow.png',
    '$_assetPath/Cloud Rainbow-1.png',
    '$_assetPath/Cloud Sun.png',
    '$_assetPath/Cloud Sun-1.png',
    '$_assetPath/Cloud-1.png',
    '$_assetPath/Cloud-2.png',
    '$_assetPath/Cloud-3.png',
    '$_assetPath/Cloud-4.png',
    '$_assetPath/Comment Question.png',
    '$_assetPath/Crown.png',
    '$_assetPath/Cupcake.png',
    '$_assetPath/Cupcake-1.png',
    '$_assetPath/Dandelion.png',
    '$_assetPath/Dizziness.png',
    '$_assetPath/Dizziness-1.png',
    '$_assetPath/Exclamation Bubble.png',
    '$_assetPath/Exclamation Questions Bubble.png',
    '$_assetPath/Feather.png',
    '$_assetPath/Feather-1.png',
    '$_assetPath/Feather-2.png',
    '$_assetPath/Feather-3.png',
    '$_assetPath/Feather-4.png',
    '$_assetPath/Floral.png',
    '$_assetPath/Floral Banner.png',
    '$_assetPath/Floral-1.png',
    '$_assetPath/Floral-2.png',
    '$_assetPath/Floral-3.png',
    '$_assetPath/Flower.png',
    '$_assetPath/Flower - Outline - 1.png',
    '$_assetPath/Flower - Outline - 3.png',
    '$_assetPath/Flower - Outline - 4.png',
    '$_assetPath/Flower - Outline - 5.png',
    '$_assetPath/Flower - Outline - 6.png',
    '$_assetPath/Flower - Outline - 7.png',
    '$_assetPath/Flower Cup.png',
    '$_assetPath/Flower Pot.png',
    '$_assetPath/Flower Pot-1.png',
    '$_assetPath/Flower Pot-2.png',
    '$_assetPath/Flower Pot-3.png',
    '$_assetPath/Flower-1.png',
    '$_assetPath/Flower-2.png',
    '$_assetPath/Flower-3.png',
    '$_assetPath/Flower-4.png',
    '$_assetPath/Flower-5.png',
    '$_assetPath/Flower-6.png',
    '$_assetPath/French Fries.png',
    '$_assetPath/Globe.png',
    '$_assetPath/Globe Banner.png',
    '$_assetPath/Globe-1.png',
    '$_assetPath/Globe-2.png',
    '$_assetPath/Happy Sun.png',
    '$_assetPath/Heart.png',
    '$_assetPath/Heart Bubble.png',
    '$_assetPath/Heart Bubble-1.png',
    '$_assetPath/Heart Bubble-2.png',
    '$_assetPath/Heart Bubble-3.png',
    '$_assetPath/Heart Bubble-4.png',
    '$_assetPath/Heart-1.png',
    '$_assetPath/Heart-2.png',
    '$_assetPath/Heart-3.png',
    '$_assetPath/Heart-4.png',
    '$_assetPath/Heart-5.png',
    '$_assetPath/Heart-6.png',
    '$_assetPath/Heart-7.png',
    '$_assetPath/Heart-8.png',
    '$_assetPath/Heart-9.png',
    '$_assetPath/Heart-10.png',
    '$_assetPath/Heart-11.png',
    '$_assetPath/Hi Bubble.png',
    '$_assetPath/Indian.png',
    '$_assetPath/leaf.png',
    '$_assetPath/leaf-1.png',
    '$_assetPath/Leaf-2.png',
    '$_assetPath/Leaf-3.png',
    '$_assetPath/Leaf-4.png',
    '$_assetPath/Leaf-5.png',
    '$_assetPath/Lightbulb.png',
    '$_assetPath/Like.png',
    '$_assetPath/Like-1.png',
    '$_assetPath/Likes.png',
    '$_assetPath/Menu Bars.png',
    '$_assetPath/Moon.png',
    '$_assetPath/Moon-1.png',
    '$_assetPath/Palm Tree.png',
    '$_assetPath/Perfume.png',
    '$_assetPath/Pizza.png',
    '$_assetPath/Pizza-1.png',
    '$_assetPath/Planet.png',
    '$_assetPath/Pyramid.png',
    '$_assetPath/Pyramid-1.png',
    '$_assetPath/Pyramid-2.png',
    '$_assetPath/Rain.png',
    '$_assetPath/Rain-1.png',
    '$_assetPath/Rss.png',
    '$_assetPath/Search.png',
    '$_assetPath/Shield.png',
    '$_assetPath/Ship.png',
    '$_assetPath/Signal Stream.png',
    '$_assetPath/Socks.png',
    '$_assetPath/Spark.png',
  ];

  static String getRandomIllustration() {
    final random = Random().nextInt(illustrations.length);
    return illustrations[random];
  }

}
