name: Deploy App to Google Play

on:
  workflow_run:
    workflows:
      - Create GitHub Release
    types:
      - completed

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Установка Flutter SDK
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Настройка Android SDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      - name: Run Flutter doctor
        run: flutter doctor

      # Сборка APK файла
      - name: Build APK
        run: flutter build apk --release

      # Подготовка к деплою в Google Play
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.warioddly.days
          releaseFiles: build/app/outputs/flutter-apk/app-release.apk
          track: internal

      # Опционально: Очистка после сборки
      - name: Clean up
        run: flutter clean
