name: Deploy App to Google Play

on:
  workflow_run:
    workflows:
      - Create GitHub Release
    types:
      - completed

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Установка Flutter SDK
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release

      # Подготовка к деплою в Google Play
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.warioddly.days
          releaseFiles: app-release/app-release.apk
          track: internal

      # Опционально: Очистка после сборки
      - name: Clean up
        run: flutter clean

      - name: Delete artifact
        run: |
          ARTIFACT_ID=$(gh api -X GET /repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[] | select(.name == "app-release") | .id')
          gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
